//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGBOSTON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Userlogin
    {
        public string UserId { get; set; }
        public string Password { get; set; }
    }
}
